import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';

const $ = selector => document.querySelector(selector);
const uid = () => crypto.randomUUID();
const dbName = 'evidenceboard';
let db, state, pdfs = new Map(), currentPdf, currentPage = 1, pageScale = 1.15;
let tool = 'select', selected = new Set(), selectionAnchor = null, saveTimer, inkStroke = null;

const blankState = () => ({version: 1, name: 'EvidenceBoard', documents: [], boards: [{id: uid(), title: 'Board', items: [], links: [], ink: [], view: {x: 0, y: 0, scale: 1}}], activeBoardId: null, annotations: []});
const board = () => state.boards.find(b => b.id === state.activeBoardId) || state.boards[0];

function openDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(dbName, 1); request.onupgradeneeded = () => { request.result.createObjectStore('projects'); request.result.createObjectStore('files'); }; request.onsuccess = () => { db = request.result; resolve(); }; request.onerror = () => reject(request.error); }); }
function tx(store, mode = 'readonly') { return db.transaction(store, mode).objectStore(store); }
function requestResult(req) { return new Promise((resolve, reject) => { req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); }
async function load() { state = await requestResult(tx('projects').get('main')) || blankState(); if (!state.activeBoardId) state.activeBoardId = state.boards[0].id; for (const doc of state.documents) { const file = await requestResult(tx('files').get(doc.id)); if (file) await openPdf(doc, file, false); } render(); }
function save() { clearTimeout(saveTimer); saveTimer = setTimeout(async () => { await requestResult(tx('projects', 'readwrite').put(state, 'main')); }, 350); }

async function openPdf(meta, file, select = true) { try { const data = await file.arrayBuffer(); const pdf = await pdfjsLib.getDocument({data}).promise; pdfs.set(meta.id, {pdf, file, pageTexts: []}); meta.pages = pdf.numPages; if (select) { state.activeDocumentId = meta.id; currentPdf = pdfs.get(meta.id); currentPage = 1; } } catch (error) { console.error(error); alert(`Could not open “${meta.title}”.`); } }
async function addFiles(files) { for (const file of files) { const meta = {id: uid(), title: file.name.replace(/\.pdf$/i, ''), filename: file.name, pages: 0, createdAt: Date.now()}; state.documents.push(meta); await requestResult(tx('files', 'readwrite').put(file, meta.id)); await openPdf(meta, file, true); } save(); render(); await renderPdf(); }

function render() { renderLists(); renderBoard(); renderToolbar(); }
function renderLists() { const list = $('#document-list'); list.innerHTML = state.documents.length ? '' : '<p class="empty">Add a PDF to begin.</p>'; const picker = $('#doc-picker'); picker.innerHTML = '<option value="">Choose a document</option>'; state.documents.forEach(doc => { const active = doc.id === state.activeDocumentId; const button = document.createElement('button'); button.className = `doc-entry${active ? ' active' : ''}`; button.textContent = doc.title; button.title = doc.filename; button.onclick = () => chooseDoc(doc.id); list.append(button); const option = new Option(doc.title, doc.id, active, active); picker.add(option); }); const boards = $('#board-list'); boards.innerHTML = ''; state.boards.forEach(b => { const item = document.createElement('button'); item.className = `board-entry${b.id === board().id ? ' active' : ''}`; item.textContent = b.title; item.onclick = () => { state.activeBoardId = b.id; selected.clear(); save(); render(); }; boards.append(item); }); $('#board-title').textContent = board().title; }
function renderToolbar() { $('#project-name').firstChild.nodeValue = `${state.name} `; $('#page-label').textContent = currentPdf ? `${currentPage} / ${currentPdf.pdf.numPages}` : '—'; $('#zoom-label').textContent = `${Math.round(pageScale * 100)}%`; }
async function chooseDoc(id) { state.activeDocumentId = id; currentPdf = pdfs.get(id); currentPage = 1; save(); render(); await renderPdf(); }

async function pageText(docId, page) { const entry = pdfs.get(docId); if (!entry) return ''; if (!entry.pageTexts[page]) { const pg = await entry.pdf.getPage(page); const content = await pg.getTextContent(); entry.pageTexts[page] = content.items.map(x => x.str).join(' '); } return entry.pageTexts[page]; }
async function renderPdf() { const stage = $('#reader-stage'); if (!currentPdf) return; stage.innerHTML = '<div class="welcome"><p>Loading PDF…</p></div>'; const pdfPage = await currentPdf.pdf.getPage(currentPage); const viewport = pdfPage.getViewport({scale: pageScale}); const wrap = document.createElement('div'); wrap.className = 'pdf-page'; wrap.dataset.page = currentPage; const canvas = document.createElement('canvas'); const ratio = Math.min(devicePixelRatio || 1, 2); canvas.width = Math.floor(viewport.width * ratio); canvas.height = Math.floor(viewport.height * ratio); canvas.style.width = `${viewport.width}px`; canvas.style.height = `${viewport.height}px`; const ctx = canvas.getContext('2d'); await pdfPage.render({canvasContext: ctx, viewport, transform: ratio === 1 ? null : [ratio, 0, 0, ratio, 0, 0]}).promise; const textLayer = document.createElement('div'); textLayer.className = 'textLayer'; textLayer.style.width = `${viewport.width}px`; textLayer.style.height = `${viewport.height}px`; const textContent = await pdfPage.getTextContent(); await pdfjsLib.renderTextLayer({textContentSource: textContent, container: textLayer, viewport}).promise; wrap.append(canvas, textLayer); stage.innerHTML = ''; stage.append(wrap); await pageText(state.activeDocumentId, currentPage); renderToolbar(); }

function renderBoard() { const b = board(); const root = $('#board'); root.style.transform = `translate(${b.view.x}px, ${b.view.y}px) scale(${b.view.scale})`; const items = $('#items'); items.innerHTML = ''; for (const item of b.items) { const el = $('#item-template').content.firstElementChild.cloneNode(true); el.dataset.id = item.id; el.classList.add(item.kind); if (selected.has(item.id)) el.classList.add('selected'); el.style.left = `${item.x}px`; el.style.top = `${item.y}px`; const body = el.querySelector('.item-body'); body.textContent = item.text; if (item.kind === 'note') { body.contentEditable = 'true'; body.addEventListener('input', () => { item.text = body.textContent; save(); }); } const meta = el.querySelector('.item-meta'); meta.textContent = item.kind === 'excerpt' ? `${item.source.title} · p. ${item.source.page}` : (item.tags || []).map(t => `#${t}`).join(' '); el.querySelector('.item-delete').onclick = event => { event.stopPropagation(); deleteItem(item.id); }; el.addEventListener('click', event => { if (event.target.closest('.item-delete') || document.activeElement === body) return; selectItem(item.id, event.shiftKey); }); el.addEventListener('dblclick', () => { if (item.source) jumpToSource(item.source); }); makeDraggable(el, item); items.append(el); } drawLinks(); drawInk(); }
function selectItem(id, additive = false) { if (!additive) selected.clear(); selected.has(id) && additive ? selected.delete(id) : selected.add(id); renderBoard(); }
function deleteItem(id) { const b = board(); b.items = b.items.filter(x => x.id !== id); b.links = b.links.filter(x => x.from !== id && x.to !== id); selected.delete(id); save(); renderBoard(); }
function makeDraggable(el, item) { let start; el.addEventListener('pointerdown', event => { if (tool !== 'select' || event.target.closest('[contenteditable]') || event.target.closest('button')) return; start = {x: event.clientX, y: event.clientY, ix: item.x, iy: item.y}; el.setPointerCapture(event.pointerId); event.preventDefault(); }); el.addEventListener('pointermove', event => { if (!start) return; const s = board().view.scale; item.x = Math.max(0, start.ix + (event.clientX - start.x) / s); item.y = Math.max(0, start.iy + (event.clientY - start.y) / s); el.style.left = `${item.x}px`; el.style.top = `${item.y}px`; drawLinks(); }); el.addEventListener('pointerup', () => { if (start) { start = null; save(); } }); }
function drawLinks() { const svg = $('#links'), b = board(); svg.innerHTML = ''; b.links.forEach(link => { const from = b.items.find(x => x.id === link.from), to = b.items.find(x => x.id === link.to); if (!from || !to) return; const x1 = from.x + 103, y1 = from.y + 44, x2 = to.x + 103, y2 = to.y + 44; const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.setAttribute('d', `M ${x1} ${y1} C ${x1 + (x2-x1)*.45} ${y1}, ${x1 + (x2-x1)*.55} ${y2}, ${x2} ${y2}`); svg.append(path); if (link.label) { const label = document.createElementNS('http://www.w3.org/2000/svg', 'text'); label.textContent = link.label; label.setAttribute('x', (x1+x2)/2); label.setAttribute('y', (y1+y2)/2 - 5); label.setAttribute('text-anchor','middle'); label.setAttribute('fill','#275f58'); label.setAttribute('font-size','14'); svg.append(label); } }); }
function drawInk() { const canvas = $('#ink'), ctx = canvas.getContext('2d'); canvas.width = 3000; canvas.height = 2200; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.strokeStyle = '#34332b'; ctx.lineWidth = 3; board().ink.forEach(stroke => { ctx.beginPath(); stroke.points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); }); }

function addNote() { const b = board(); const n = b.items.length; b.items.push({id: uid(), kind: 'note', text: 'New thought', x: 160 + (n%4)*45, y: 150 + (n%5)*38, tags: []}); save(); renderBoard(); }
function createExcerpt() { if (!selectionAnchor) return; const b = board(), n = b.items.length; b.items.push({id: uid(), kind: 'excerpt', text: selectionAnchor.quote, x: 170 + (n%4)*55, y: 130 + (n%5)*45, source: selectionAnchor, tags: []}); selectionAnchor = null; $('#selection-menu')?.remove(); save(); renderBoard(); }
async function jumpToSource(source) { await chooseDoc(source.documentId); currentPage = source.page; await renderPdf(); setTimeout(() => { const page = $('.pdf-page'); page?.scrollIntoView({behavior:'smooth', block:'center'}); }, 100); }
function connectSelected() { if (selected.size !== 2) return alert('Select exactly two cards (tap one, then Shift-tap another) before connecting.'); const [from, to] = [...selected]; const label = prompt('Relationship label (optional):') || ''; board().links.push({id: uid(), from, to, label}); selected.clear(); save(); renderBoard(); }

async function search(query) { if (!query.trim()) return renderPdf(); const needle = query.toLowerCase(); const hits = []; for (const doc of state.documents) for (let p=1;p<=doc.pages;p++) { const text = await pageText(doc.id,p); const at = text.toLowerCase().indexOf(needle); if (at >= 0) hits.push({doc,p, snippet: text.slice(Math.max(0,at-55),at+query.length+85)}); } const noteHits = state.boards.flatMap(b => b.items.filter(i => i.text.toLowerCase().includes(needle)).map(i => ({board:b,item:i}))); const stage = $('#reader-stage'); stage.innerHTML = `<div class="welcome"><h2>${hits.length + noteHits.length} result${hits.length + noteHits.length === 1 ? '' : 's'}</h2></div>`; const box = stage.firstElementChild; hits.forEach(hit => { const btn=document.createElement('button'); btn.className='doc-entry'; btn.textContent=`${hit.doc.title}, p. ${hit.p}: ${hit.snippet}`; btn.onclick=async()=>{await chooseDoc(hit.doc.id);currentPage=hit.p;await renderPdf();}; box.append(btn); }); noteHits.forEach(hit=>{const btn=document.createElement('button');btn.className='doc-entry';btn.textContent=`Note on ${hit.board.title}: ${hit.item.text}`;btn.onclick=()=>{state.activeBoardId=hit.board.id;selected=new Set([hit.item.id]);render();};box.append(btn);}); }
function exportOutline() { let out = `# ${state.name}\n\n`; state.boards.forEach(b => { out += `## ${b.title}\n\n`; b.items.forEach(i => { out += `- ${i.kind === 'excerpt' ? '> ' : ''}${i.text.replace(/\n/g,' ')}${i.source ? ` — ${i.source.title}, p. ${i.source.page}` : ''}\n`; }); out += '\n'; }); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([out],{type:'text/markdown'})); a.download = `${state.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase() || 'evidenceboard'}-outline.md`; a.click(); URL.revokeObjectURL(a.href); }

function showSelectionMenu(event) { const sel = getSelection(); const quote = sel?.toString().trim(); if (!quote || !currentPdf) return; const range = sel.getRangeAt(0); if (!range.commonAncestorContainer.parentElement?.closest('.textLayer')) return; $('#selection-menu')?.remove(); selectionAnchor = {documentId: state.activeDocumentId, page: currentPage, quote, title: state.documents.find(d=>d.id===state.activeDocumentId).title}; const menu = document.createElement('div'); menu.id='selection-menu'; menu.className='selection-popover'; menu.style.left=`${Math.min(event.clientX, innerWidth-150)}px`; menu.style.top=`${Math.max(8,event.clientY-42)}px`; menu.innerHTML='<button id="make-excerpt">Make excerpt</button><button id="make-highlight">Highlight</button>'; document.body.append(menu); $('#make-excerpt').onclick=createExcerpt; $('#make-highlight').onclick=()=>{state.annotations.push({id:uid(),...selectionAnchor,kind:'highlight',createdAt:Date.now()});save();menu.remove();sel.removeAllRanges();}; }

function bind() { $('#file-input').onchange = event => addFiles([...event.target.files]); $('#doc-picker').onchange = event => chooseDoc(event.target.value); $('#prev-page').onclick = async()=>{if(currentPdf&&currentPage>1){currentPage--;await renderPdf();}}; $('#next-page').onclick = async()=>{if(currentPdf&&currentPage<currentPdf.pdf.numPages){currentPage++;await renderPdf();}}; $('#zoom-in').onclick=async()=>{if(currentPdf){pageScale=Math.min(2.3,pageScale+.15);await renderPdf();}}; $('#zoom-out').onclick=async()=>{if(currentPdf){pageScale=Math.max(.65,pageScale-.15);await renderPdf();}}; $('#new-note').onclick=addNote; $('#connect').onclick=connectSelected; $('#export').onclick=exportOutline; $('#project-name').onclick=()=>{const n=prompt('Project name',state.name);if(n){state.name=n;save();render();}}; $('#new-board').onclick=()=>{const title=prompt('Board name','New board');if(title){const b={id:uid(),title,items:[],links:[],ink:[],view:{x:0,y:0,scale:1}};state.boards.push(b);state.activeBoardId=b.id;save();render();}}; $('#fit-board').onclick=()=>{board().view={x:0,y:0,scale:1};save();renderBoard();}; document.querySelectorAll('.tool').forEach(btn=>btn.onclick=()=>{tool=btn.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('selected',x===btn));$('#ink').style.pointerEvents=tool==='ink'?'auto':'none';}); let timer; $('#search-input').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>search(e.target.value),350);}; $('#reader-stage').addEventListener('pointerup', showSelectionMenu); bindBoardGestures(); }
function bindBoardGestures() { const viewport=$('#board-viewport'); let pan; viewport.addEventListener('pointerdown',e=>{if(tool==='pan'){pan={x:e.clientX,y:e.clientY,vx:board().view.x,vy:board().view.y};viewport.setPointerCapture(e.pointerId);}}); viewport.addEventListener('pointermove',e=>{if(pan){board().view.x=pan.vx+e.clientX-pan.x;board().view.y=pan.vy+e.clientY-pan.y;renderBoard();}}); viewport.addEventListener('pointerup',()=>{if(pan){pan=null;save();}}); viewport.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();const b=board();b.view.scale=Math.max(.45,Math.min(1.8,b.view.scale*(e.deltaY>0?.92:1.08)));renderBoard();save();}},{passive:false}); const canvas=$('#ink'); canvas.addEventListener('pointerdown',e=>{if(tool!=='ink')return;const r=canvas.getBoundingClientRect(),b=board(),s=b.view.scale;inkStroke={points:[{x:(e.clientX-r.left-b.view.x)/s,y:(e.clientY-r.top-b.view.y)/s}]};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!inkStroke)return;const r=canvas.getBoundingClientRect(),b=board(),s=b.view.scale;inkStroke.points.push({x:(e.clientX-r.left-b.view.x)/s,y:(e.clientY-r.top-b.view.y)/s});const tmp=board().ink;tmp.push(inkStroke);drawInk();tmp.pop();});canvas.addEventListener('pointerup',()=>{if(inkStroke){board().ink.push(inkStroke);inkStroke=null;save();drawInk();}}); }

await openDb(); await load(); bind(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
